### ISSUE TITLE
magent2 data migration not functioning

### ISSUE THREAD

**Issue by vpiyappan** [ubertheme/magento2_data_migration#1]
I installed magento2 data migration module in  windows 7 magento 2 version 0.74.0-beta13. While I try to migrate the data it shows "Data processing. Please wait." for long time.
![image](https://cloud.githubusercontent.com/assets/11790408/8774706/a27dce02-2efe-11e5-9413-99a30738998d.png)

**Comment by vpiyappan** [comment]
I created "assets" folder under "migrate_data_tool" with full access, the migration went well upto step 9.  But i got error finally as below.

![image](https://cloud.githubusercontent.com/assets/11790408/8775952/ce03f374-2f0a-11e5-810e-85d4163ccc3d.png)

**Comment by quynhvv** [comment]
@vpiyappan:
What version of your Magento1 and Magento2?
Please tell me what version of this tool (magento2_data_migration) you are
using?

On Mon, Jul 20, 2015 at 5:42 AM, vpiyappan notifications@github.com wrote:

> I created "assets" folder under "migrate_data_tool" with full access, the
> migration went well upto step 9. But i got error finally as below.
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/11790408/8775952/ce03f374-2f0a-11e5-810e-85d4163ccc3d.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/1#issuecomment-122872084
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vpiyappan** [comment]
Magento 1.9.0.0 and Magento ver. 0.74.0-beta13

magento2_data_migration Version0.1.14

**Comment by quynhvv** [comment]
Sorry, we have not yet released this tool for Magento2 ver. 0.74.0-beta13

You can use magento2_data_migration Version0.1.14
https://github.com/ubertheme/magento2_data_migration/releases/tag/Version0.1.14
for
- Magento 2 version 0.74.0 beta 12
- Magento Community Edition (CE) versions: 1.6.x, 1.7.x, 1.8.x, 1.9.x

On Tue, Jul 21, 2015 at 2:34 PM, vpiyappan notifications@github.com wrote:

> Magento 1.9.0.0 and Magento ver. 0.74.0-beta13
> 
> magento2_data_migration Version0.1.14
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/1#issuecomment-123199627
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vpiyappan** [comment]
Thank you for your support, I will try using Magento 2 version 0.74.0 beta 12

**Comment by quynhvv** [comment]
Yes, let's pm me if you get any issues.

On Tue, Jul 21, 2015 at 5:22 PM, vpiyappan notifications@github.com wrote:

> Thank you for your support, I will try using Magento 2 version 0.74.0 beta
> 12
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/1#issuecomment-123253901
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002
