### ISSUE TITLE
Attribute Migration 

### ISSUE THREAD

**Issue by derdeakon** [ubertheme/magento2_data_migration#10]
Hello,

i want to migrate my multistore in my new magento2. I follow your Migration Guide Step by Step but in Step 3 i got an error Message.

Could You help me with that.

I use Magento 1.9.0.1 and last release from Mage2
.
![error](https://cloud.githubusercontent.com/assets/7261600/11395471/a962d592-936b-11e5-97e9-9059dcf8d711.PNG)

Thanks for your help

**Comment by quynhvv** [comment]
Hi derdeakon,
To solve the issue as you said let's do steps bellow:
Step 1: Manual reset the step 3 by URL: `http://URL_TO_THIS_TOOL/migrate/reset/step/3`
Step 2: 
Open the PHP file at `protected/controllers/MigrateController.php`
and find to the code line 401: `$attribute_group2->attribute_group_code = null;`
and replace it by code lines:

```
$attributeGroupCode = trim(preg_replace('/[^a-z0-9]+/', '-', strtolower($attribute_group->attribute_group_name)), '-');
$attribute_group2->attribute_group_code = $attributeGroupCode;

```

and re-start migration on this step.

Let's do it and tell me know how it goes.
Regards,
quynhvv

**Comment by derdeakon** [comment]
Hi quynhvv,

your fix works for me. Thank you

**Comment by quynhvv** [comment]
@derdeakon: Yes, that is a good news.
Can you tell me know:
How many objects data in your working?
Categories?
Products?
Sales Orders?
...
Regards,
quynhvv

**Comment by derdeakon** [comment]
old System Magento 1.9.0.1
Categories See Attachements
![mage1](https://cloud.githubusercontent.com/assets/7261600/11437369/824d036e-94ed-11e5-9609-429684a10212.PNG)
Products: 589
Sales Order: 51

new Magento 2:
Categories See Attachements
![mage2](https://cloud.githubusercontent.com/assets/7261600/11437561/fd29fa14-94ee-11e5-9b06-0db70af23df5.PNG)

Here are some prodcuts not in the correct category
Products: 589
Sales Order: 2

**Comment by derdeakon** [comment]
Hi guys, 
are here some new information about the difference between the categories? For example
Old Magento Shop 1.9 Categorie = Men 72 Products: New Magento Shop category = men 0 Products.
I don't know why there is a difference

**Comment by quynhvv** [comment]
@derdeakon : Did you re-index the data in Magento 2 after migrated successfully?

@guys: I would like to announcement that, we have just release two Magento modules for this:
- Once for Magento CE 1.x: https://docs.google.com/document/d/1FmJfDIm8u09m8T9jcCL38t3vRxcKbS7DMltaA2WFUI8/edit#heading=h.75wvj9m0za9x
- Once for Magento CE  2.0.0:
  https://github.com/ubertheme/module-ubdatamigration

You can chose 1 or 2 is optional.
Regards,
quynhvv

**Comment by derdeakon** [comment]
yes i reindexed sometime, i will try your new version now with the hope that everything works. i will give you any feedback after that

**Comment by quynhvv** [comment]
@derdeakon: Yes, let's do it and tell me know how it goes.
With Categories, we have tested with multiple root categories, multiple categories in multiple websites and stores, store views database. and everything working fine.
![categories](http://i.imgur.com/xTxlDCZ.png) ![categories2](http://i.imgur.com/F9WUFVs.png)

![website stores](http://i.imgur.com/e1r1EJd.png)
![website stores2](http://i.imgur.com/NjtgEw8.png)

![products](http://i.imgur.com/5llgng1.png)
![products2](http://i.imgur.com/ojtmJY8.png)
Regards,
quynhvv

**Comment by derdeakon** [comment]
hi quynhvv, 

the new version of your tool works for me. i have right now the correct products of my categories.

thanks

**Comment by quynhvv** [comment]
@derdeakon : Yes, that is a good news ;)
Can you tell me:
- What module you are using?
- How many data objects in your working? (Categories, Products, Sales....?)

**Comment by derdeakon** [comment]
I am using the Magento2 Data Migration version 0.1.21

Categories: 28
Products: 589
Sales: 51

I have another Problem now. The Categorieimport works fine, but products of 2 categories woudln't show in the frontend.
Setup of old MagentoCategory: show Products in display settings
Setup of new MagentoCategory: show Products in display settings

but there were no products showing. If i select a subcategory in the layered navigation the products were shown.
any Help

**Comment by quynhvv** [comment]
@derdeakon : Seem you haven't re-index yet the data in Magento 2?

**Comment by derdeakon** [comment]
Yes i have re-index after the succesfull import directly. Multiple.
