### ISSUE TITLE
No Sales Data

### ISSUE THREAD

**Issue by simadesign** [ubertheme/magento2_data_migration#11]
Hi, first of all great work. The migration-Tools works even better than the official console version.

![unbenannt](https://cloud.githubusercontent.com/assets/8430372/11425613/5ecaa212-9456-11e5-9e24-4e7ebcf6ed92.JPG)

But after the migration steps my backend show no sales data:

![unbenannt1](https://cloud.githubusercontent.com/assets/8430372/11425614/6211973c-9456-11e5-9366-4bbad59f005f.JPG)

**Comment by quynhvv** [comment]
Hi simadesign,
Please tell me know,
What versions of Magento 1 and Magento 2 in your working?
What version of this tool you are using?
Did you do full steps of this tool at https://github.com/ubertheme/magento2_data_migration/blob/master/README.md

Did you make re-index the database of Magento 2 website after migration finished?

Regards,
quynhvv

**Comment by simadesign** [comment]
Version of Magento 1 is 1.9.1.0 and Version of Magento is 2.0.0.
Migration tool is 0.1.20
Yes, I make the re-index with the consol.

**Comment by quynhvv** [comment]
Hi simadesign,

How about other data: Websites, Stores, Categories, Products, Customers,
...?

Regards,
quynhvv

On Thu, Nov 26, 2015 at 11:19 PM, simadesign notifications@github.com
wrote:

> Version of Magento 1 is 1.9.1.0 and Version of Magento is 2.0.0.
> Migration tool is 0.1.20
> Yes, I make the re-index with the consol.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/11#issuecomment-159952218
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by simadesign** [comment]
At the list of products magento gives me the error-msg: Could not determine temp directory, please specify a cache_dir manually

The Categories, stores and customers are ok.

**Comment by quynhvv** [comment]
@simadesign :

> At the list of products magento gives me the error-msg: Could not determine temp directory, please >specify a cache_dir manually

Let's re-check the folder permission in your Magento2. Seem you have not yet make write able for folder at path: app/var/*

> No sale data 

=> Let's make manual reset on this step by URL: http://URL_TO_THIS_TOOL/migrate/reset/step/7
and re-start data migration on this step.

Let's do it and tell me know how it goes.
Regards,
quynhvv.

**Comment by quynhvv** [comment]
@simadesign :
I have detected the root of issue about Sale Data as you said. 
That because have some new validate rules in table `sales_order` of Magento 2 database. In this case the max length of `store_name` attribute allow in Magento 2 is 32 chars, but your data in Magento 1 database was greater 32 chars. This is reason the tool can't insert data of sale_order.
To solve this issue you can do steps bellow:
- Open the file at `/protected/controllers/MigrateController.php` and find to the block code:

```
foreach ($sales_order2->attributes as $key => $value){
                                    if (isset($sales_order->$key)){
                                        $sales_order2->$key = $sales_order->$key;
                                    }
                                }
```

and replace it by block code:

```
foreach ($sales_order2->attributes as $key => $value){
                                    if (isset($sales_order->$key)){
                                        /**
                                         * Magento 2 only accept max length of store name = 32 chars
                                         * So we have to check length of store name here to split
                                         */
                                        $val = $sales_order->$key;
                                        if ( in_array($key, array('store_name')) && strlen($val) > 32) {
                                            $val = substr($val, 0, 32);
                                        }
                                        $sales_order2->$key = $val;
                                    }
                                }
```

and make manual reset the step 7 by URL: http://URL_TO_THIS_TOOL/migrate/reset/step/7

and re-start data migration on this step.

Let's do it to solve the issue as you said and tell me know how it goes after you finished.
Regards,
quynhvv

**Comment by simadesign** [comment]
I tried the new code and re-start the migration of step 7. Now the Sales-Overview sais "Could not determine temp directory, please specify a cache_dir manually", too.

I checked all the write permissions. I followed this steps:
http://devdocs.magento.com/guides/v2.0/install-gde/install/file-system-perms.html

And set the folder permissions like that:
find . -type d -exec chmod 770 {} \; && find . -type f -exec chmod 660 {} \; && chmod u+x bin/magento

But nothing changed. Same problem.... :(

**Comment by magecomp** [comment]
Worked thanks :)

**Comment by quynhvv** [comment]
Yes, that is a good news. Can you close this issue?

On Sat, Nov 28, 2015 at 7:10 PM, MageComp notifications@github.com wrote:

> Worked thanks :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/11#issuecomment-160288050
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002
