### ISSUE TITLE
Issue on 2000+ Product migration

### ISSUE THREAD

**Issue by vickkeane** [ubertheme/magento2_data_migration#13]
![issue1](https://cloud.githubusercontent.com/assets/15953328/11471086/c0a1438a-9788-11e5-9003-5caa7c3bdfa1.png)

Hi
Glad to you , Here i had import product,categories from magento1.9 to 2.0 .
The products are listing in below the category products , but same i try to list the product in 
admin->catalog . it shows 
"Item (Magento\Catalog\Model\Product\Interceptor) with the same id "2" already exist"

I try fresh magento2 without sample data .

Thanks

**Comment by quynhvv** [comment]
Hi vickkeane,
Did you make reindex the database of Magento 2 after data migrated successfully?
Regards,
quynhvv

**Comment by vickkeane** [comment]
Hi
Yes i had reindex, clear cache and delete folder inside var and then compile 
Thanks

**Comment by quynhvv** [comment]
@vickkeane: 
Does your Magento 1 website re-index data success now?
What version of this tool you are using?
Can you show me the screenshot to specify that, you have make re-index data successfully in your Magento 1 and Magento 2 ?
Regards,
quynhvv

**Comment by quienti** [comment]
Hello, i have the same problem, maybe this error can be caused by multiple store.

migrate from magento 1.9.2.2 to magento 2.0 and your last master.
Magento 1 and 2 have been re- indexed.

Thanks

**Comment by quynhvv** [comment]
@quienti : 
I have tested this tool with multiple stores but i don't see the issue as you said.
Can you make a dump of your Magento 1 database and share to me?
I need a closer look to detect the root of issue as you said.
Regards,
quynhvv

**Comment by quienti** [comment]
Sorry i can't dump my database because it contains a lot of private data.

maybe can i send you only  cataloginventory_stock_item and catalog_product_entity ?

**Comment by quynhvv** [comment]
@quienti: So be hard to help you on this issue.
Did you do the step as the screenshot?: 
![test](http://i.imgur.com/Z0I0rTb.png)

Regards,
quynhvv

**Comment by quienti** [comment]
yes i follow your guide and i did migration 4 times, but always same problem. Is it possible to send you only tables you need?

**Comment by quynhvv** [comment]
@quienti: 

> maybe can i send you only cataloginventory_stock_item and catalog_product_entity ?

=> I can't make a test for that.

Can you show me the screenshots to specify that you have re-index the data successfully in your Magento 1 and Magento 2?

Regards,
quynhvv

**Comment by quienti** [comment]
Magento 1 :
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/11499979/4e588110-982a-11e5-836e-97a13dc381df.jpg)

Magento 2 :
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11499953/181c2746-982a-11e5-846a-9d1d9492dc9b.jpg)

**Comment by vickkeane** [comment]
Hi 

How to create a simple product pro grammatically in magento2 .
In magento1.X we use app/mage.php 
Thank s

**Comment by quynhvv** [comment]
@quienti : 
Did you see, there is a issue in the screenshot of Magento 2? 'Requested store is not found'
And I don't see you select objects to reindex in Magento 1 screenshot.
Can you select all objects and reindex in Magento 1?
Regards,
quynhvv

**Comment by quynhvv** [comment]
@vickkeane : You can find it at: `vendor/magento/module-catalog`

**Comment by quienti** [comment]
yes i see it but I thought it was normal, any idea to fix this problem?

when i select only 1 store in your migrate_data_tool i can see my product and i have not this error

"Item (Magento\Catalog\Model\Product\Interceptor) with the same id "26" already exist"

in screenshot of magento 1 it was an mistake but when I migrated my database it was re-indexed

![aze](https://cloud.githubusercontent.com/assets/7326954/11505837/a3f51b5c-984c-11e5-8253-e153e63d2961.PNG)

**Comment by quynhvv** [comment]
@quienti:
I need a closer look to detect the root of issue in your case. 
Can you share me a database backup of your Magento1?
Regards,
quynhvv

**Comment by quienti** [comment]
I can't diffuse my database on internet because this is a professional website. but i will restart migration and check step by step if magento is working.

**Comment by quynhvv** [comment]
@quienti : 

> but i will restart migration and check step by step if magento is working.

I have tested this tool with database contain multiple stores, store views and i don't see the issue as you said.
Yes, let's do it and tell me know how it goes.

**Comment by quienti** [comment]
Ok, so :

Step 1 : Database setting => no problem
Step 2 : Website/Store => Problem with ID
![sans titre 4](https://cloud.githubusercontent.com/assets/7326954/11527713/e1ad36f0-98e2-11e5-94be-9d90c2cfc422.jpg)

Here, in "Store table", my second store have ID 2, but in my other table, it's ID 3 (It's ID 3 because in Magento 1, I have 2 store with ID 1 and 3)

But, I can correct this problem when I change my ID 2 by 3

Step 3 : Attributes => Migration work fine, but after this

> Re-save all the Attribute Sets (Stores/Attributes/Attribute Set) migrated in the back-end of your
> Magento 2 website. (Open the Attribute Set, edit information of it if needed and click the save
> button)
> Reindex all data via SSH or Command line
> Remove all folders and files in WEB_ROOT_PATH\your_magento2_folder\var but take the 
> .htaccess file.
> Remove all folders and files in WEB_ROOT_PATH\your_magento2_folder\pub\static but take the
> .htaccess file.

Impossible for me to create an article
![sans titre 5](https://cloud.githubusercontent.com/assets/7326954/11527927/0dc46abe-98e4-11e5-9e31-d9084bb3c019.jpg)

Step 4 : Categories => No problem and all categories are migrated

Step 5 : Products => In progress...

**Comment by quynhvv** [comment]
@quienti:

> Here, in "Store table", my second store have ID 2, but in my other table, it's ID 3 (It's ID 3 because in Magento 1, I have 2 store with ID 1 and 3)

That isn't a issue. That working fine. We have changed the store_id in migration store views.
We will find and map store views by store code ;)
=> You shouldn't manual change the store_id after migrated.

Have a look again ;)

Regards,
quynhvv

**Comment by quienti** [comment]
Okay, no problem !

And for my attribute ? Do you have an idea ?

And actually, my products are still being migrated... But I sure, all my products will migrate, but I will have this error in Magento 2 backend when I will look my products =>

> "Item (Magento\Catalog\Model\Product\Interceptor) with the same id "26" already exist"

Edit 1 : 

Step 5 finished, all products are migrated but this error in magento backend

> "Item (Magento\Catalog\Model\Product\Interceptor) with the same id "26" already exist"

Step 6 : Customer => I have an issue here but I will fix this before start this step
![capture 1](https://cloud.githubusercontent.com/assets/7326954/11530333/fc0e7124-98f3-11e5-9d4f-714df714b252.PNG)
Because, in Magento 1, I have 2 customer group with ID 1 and 2
But in Magento 2, there are already 4 groups from 1 to 3
So, I change ID in my database and I start this migration
![sans titre 6](https://cloud.githubusercontent.com/assets/7326954/11530324/eba25ef4-98f3-11e5-80e2-461138ce61ec.jpg)

**Comment by quynhvv** [comment]
![image](https://cloud.githubusercontent.com/assets/10073722/11535848/59dd689c-9948-11e5-8d1f-071da0c22c8e.png)
=> See the screenshot, seem you are using the old code of this tool.
Code in the line number = 1765 not like the latest code at same like at 
https://github.com/ubertheme/magento2_data_migration/blob/master/protected/controllers/MigrateController.php
and you shouldn't manual edit the customer group id, the migration tool will auto map this by `customer_group_id` and `customer_group_code`

Please have a look again and update the latest all code of this tool at master branch.
Regards,
Mall.

**Comment by quienti** [comment]
Yes it's because this is an old screenshot, but even with your latest code i have the same issue. I solves this problem by manually editing my group

**Comment by quienti** [comment]
So, my migration is done !

I have 2 issues :

I can't create a product after I migrated my attributes
![sans titre 5](https://cloud.githubusercontent.com/assets/7326954/11539327/cd274c2c-9926-11e5-85e5-288e85a47e1b.jpg)

And after I migrated my products, I have is problem
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11539328/cd2802de-9926-11e5-98c8-4c21990c0fc4.jpg)

For other steps, I have no problem

**Comment by quynhvv** [comment]
Did you open and re-save all your attribute sets after migration finished?
Did you re-index the data?

**Comment by quynhvv** [comment]
@guys: I would like to announcement that, we have just released two Magento modules for this:
- Once for Magento CE 1.x: https://docs.google.com/document/d/1FmJfDIm8u09m8T9jcCL38t3vRxcKbS7DMltaA2WFUI8/edit#heading=h.75wvj9m0za9x
- Once for Magento CE  2.0.0:
  https://github.com/ubertheme/module-ubdatamigration

You can chose 1 or 2 is optional.
Regards,
quynhvv

**Comment by quienti** [comment]
> Did you open and re-save all your attribute sets after migration finished?
> Did you re-index the data?

Of course, no change

**Comment by quienti** [comment]
Ok, I have found my problem with attributes

In Magento 1, on "Catalog Input Type for Store Owner", it's "File"
![sans titre 2](https://cloud.githubusercontent.com/assets/7326954/11557758/b8781b2a-99ae-11e5-8e1e-eccdb56878a3.jpg)

But in Magento 2, it's "TextField"
![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11557757/b85b2826-99ae-11e5-9cb9-1719f465ea50.jpg)

So, when I remove this attribut, I can create an article !

I don't know if it's an issue...

There remains only this problem...
![](https://cloud.githubusercontent.com/assets/7326954/11539327/cd274c2c-9926-11e5-85e5-288e85a47e1b.jpg)

Edit : Another problem, all my customer account not working because they are a wrong password_hash, Magento 2 have not the same password hash like Magento 1, have you an idea ?

**Comment by quynhvv** [comment]
@quienti:

> "Item (Magento\Catalog\Model\Product\Interceptor) with the same id "26" already exist"
> I have detected the root of  issue as you said in step 5. There is a issue with `cataloginventory_stock_item` table after data migrated in case we have multiple websites.
> To solve the issue you can do:
> Open the file at `/protected/controllers/MigrateController.php`
> and find to the block code:
> 
> ```
> //cataloginventory_stock_item
>                                                         $stock_item = Mage1StockItem::model()->find("product_id = {$model->product_id} AND stock_id = {$model->stock_id}");
>                                                         if ($stock_item){
>                                                             $stock_item2 = new Mage2StockItem();
>                                                             foreach ($stock_item2->attributes as $key => $value){
>                                                                 if ($key != 'item_id' && isset($stock_item->$key)){
>                                                                     $stock_item2->$key = $stock_item->$key;
>                                                                 }
>                                                             }
>                                                             $stock_item2->website_id = $website_id;
>                                                             $stock_item2->save();
>                                                         }
> ```
> 
> and replace it by the block code:
> 
> ```
> //cataloginventory_stock_item
>                                                         $stock_item2 = Mage2StockItem::model()->find("product_id = {$model->product_id} AND stock_id = {$model->stock_id}");
>                                                         if (!$stock_item2){
>                                                             $stock_item = Mage1StockItem::model()->find("product_id = {$model->product_id} AND stock_id = {$model->stock_id}");
>                                                             if ($stock_item){
>                                                                 $stock_item2 = new Mage2StockItem();
>                                                                 foreach ($stock_item2->attributes as $key => $value){
>                                                                     if ($key != 'item_id' && isset($stock_item->$key)){
>                                                                         $stock_item2->$key = $stock_item->$key;
>                                                                     }
>                                                                 }
>                                                                 $stock_item2->website_id = $website_id;
>                                                                 $stock_item2->save();
>                                                             }
>                                                         }
> ```
> 
> and make reset the step 5

and re-start with data migration on step 5.

Let's do it to solve the issue and tell me know how it goes.
Regards,
quynhvv.

**Comment by quienti** [comment]
Awesome, I will try now

And and you any idea for this problem ?

> Edit : Another problem, all my customer account not working because they are a wrong 
> password_hash, Magento 2 have not the same password hash like Magento 1, have you an idea ?

**Comment by quynhvv** [comment]
@quienti: 

That because the Magento CE 2.0.0 or later was change method to hash password in `password_hash` field: md5 -> sha256

Let's follow the new version of this tool to solve the issue about password_hash as you said.
https://github.com/ubertheme/magento2_data_migration/releases/tag/v0.1.23

Regards,
quynhvv

**Comment by quienti** [comment]
Thanks you, 

My migration is actually on step 5. So I will update your last commit before to launch step 6

**Comment by quynhvv** [comment]
Yes, let's do it and please note that:

I would like to announcement that, we have just released one Magento 2 modules for this tool at:

https://github.com/ubertheme/module-ubdatamigration

Regards,
quynhvv

**Comment by baltechies** [comment]
I have problems after data migration
1) Product is not visible on frontend.
2) When I tried to reindex, it throw an error like "Requested store is not found".

**Comment by UberthemeTeam** [comment]
@baltechies, 
We have replied to you via this ticket: 
https://github.com/ubertheme/module-ubdatamigration/issues/33#issuecomment-240811386
Kindly follow up further there.
Regards,
Ubertheme team
