### ISSUE TITLE
Item (Magento\Catalog\Model\Product\Interceptor) with the same id "231" already exist

### ISSUE THREAD

**Issue by derdeakon** [ubertheme/magento2_data_migration#15]
Hi guys,

i am using the new version Magento2 Data Migration version 0.1.21. After the successfull import i get an error in my product management. See attached. Is there any Idea why.

![error](https://cloud.githubusercontent.com/assets/7261600/11562057/bc0b573a-99cb-11e5-904f-ce0c4307df44.PNG)

thanks for help

**Comment by quienti** [comment]
https://github.com/ubertheme/magento2_data_migration/issues/13

**Comment by quynhvv** [comment]
@derdeakon: 

I need a closer look to detect the root of issue as you said.
Can you share me a back-up of your Magento 1 database?

Regards,
quynhvv

**Comment by derdeakon** [comment]
Yes i can share you my database.

but i can not share my database in this ticket. It is a Zip an doesn't work here
Unfortunately, we don’t support that file type.

**Comment by quienti** [comment]
@derdeakon

Use dropbox to share ;)

**Comment by derdeakon** [comment]
https://www.dropbox.com/s/phyaiumju50x2cb/database.sql?dl=0

**Comment by quynhvv** [comment]
@derdeakon: What version of Magento 1 you are using for that database?

**Comment by quynhvv** [comment]
@derdeakon :

> Item (Magento\Catalog\Model\Product\Interceptor) with the same id "231" already exist
> Thank for the database you have shared.
> I have detected the root of  issue as you said in step 5. There is a issue with `cataloginventory_stock_item` table after data migrated in case we have multiple websites.
> To solve the issue you can do:
> Open the file at `/protected/controllers/MigrateController.php`
> and find to the block code:
> 
> ```
> //cataloginventory_stock_item
> $stock_item = Mage1StockItem::model()->find("product_id = {$model->product_id} AND stock_id = {$model->stock_id}");
>                                                         if ($stock_item){
>                                                             $stock_item2 = new Mage2StockItem();
>                                                             foreach ($stock_item2->attributes as $key => $value){
>                                                                 if ($key != 'item_id' && isset($stock_item->$key)){
>                                                                     $stock_item2->$key = $stock_item->$key;
>                                                                 }
>                                                             }
>                                                             $stock_item2->website_id = $website_id;
>                                                             $stock_item2->save();
>                                                         }
> ```
> 
> and replace it by the block code:
> 
> ```
> //cataloginventory_stock_item
>                                                         $stock_item2 = Mage2StockItem::model()->find("product_id = {$model->product_id} AND stock_id = {$model->stock_id}");
>                                                         if (!$stock_item2){
>                                                             $stock_item = Mage1StockItem::model()->find("product_id = {$model->product_id} AND stock_id = {$model->stock_id}");
>                                                             if ($stock_item){
>                                                                 $stock_item2 = new Mage2StockItem();
>                                                                 foreach ($stock_item2->attributes as $key => $value){
>                                                                     if ($key != 'item_id' && isset($stock_item->$key)){
>                                                                         $stock_item2->$key = $stock_item->$key;
>                                                                     }
>                                                                 }
>                                                                 $stock_item2->website_id = $website_id;
>                                                                 $stock_item2->save();
>                                                             }
>                                                         }
> ```
> 
> and make reset the step 5

and re-start with data migration on step 5.

Let's do it to solve the issue and tell me know how it goes.
Regards,
quynhvv.

**Comment by derdeakon** [comment]
Hi quynhvv,

it works fine. Thanks you. After reindex and cache my products will shown in the backend and in the correct category in the frontend. :)

**Comment by quynhvv** [comment]
@derdeakon : 
Yes, and please note that:

We have just released one Magento 2 modules for this at:

https://github.com/ubertheme/module-ubdatamigration

Regards,
quynhvv
