### ISSUE TITLE
Can´t edit any product in backend

### ISSUE THREAD

**Issue by salelsol** [ubertheme/magento2_data_migration#16]
Just installed Magento 2 stable version and migrate data tool from Magento 1.9.1 version in local machine; frontend works fine and also backend, except I can´t edit any product.
![magento2_bug_1](https://cloud.githubusercontent.com/assets/16081377/11586254/19c132e0-9a72-11e5-80c4-1e7f0f70e92f.jpg)

**Comment by quienti** [comment]
I had the same issue

Maybe you have the same problem like me

See my last comment here : https://github.com/ubertheme/magento2_data_migration/issues/13

**Comment by salelsol** [comment]
- Hi, you are fixed issue removing an attribute, but I´ve 103 attributes and I don´t kown that attribute must delete.

Best Regards
Toni Moya

**Comment by quienti** [comment]
I had an attribute with "File" type in Magento 1, and when I removed it, 

In Magento 2, you can found yours attributes in "Stores -> Attributes -> Attribute Set -> Default", and tries to remove personnal attributes 1 by 1 (I have 100 attributes like you, so it's long)

Sorry, I don't know if it's really a bug fix, so, maybe we have to wait an answer from @quynhvv

**Comment by salelsol** [comment]
- O.K. many thanks for your help, I´m working for solve this issue.

Best Regards
Toni Moya

**Comment by salelsol** [comment]
- Hi, just fixed for a particular attribute set, disabling older attribute in data importing without your corresponding associated extension.
- Many thanks for your help.

Best Regards
Toni Moya

**Comment by quynhvv** [comment]
@quienti : 

> Sorry, I don't know if it's really a bug fix, so, maybe we have to wait an answer from @quynhvv

=> The data migration tool migrated all product attributes in Magento 1 -> Magento 2 (Custom attributes and System attributes)
And there isn't function to mass delete the attributes in both Magento 1 and Magento 2 at this time.

Regards,
quynhvv

**Comment by salelsol** [comment]
- Yes but not all custom attributes are bad for all new store, in my case just attibutes without an extension associated are bad for all new store.

Best regards
Toni Moya

**Comment by quynhvv** [comment]
@salelsol: In this case you should delete that attributes, because you haven't the related extension for that in Magento 2.
Regards,
quynhvv.
