### ISSUE TITLE
Customer missing zip, phone, etc afther migration

### ISSUE THREAD

**Issue by salelsol** [ubertheme/magento2_data_migration#17]
- Customer missing zip, phone,county, etc afther migration.
- Also when I´ve trying install data migration tool lasted version i´ve this issue.
  ![customers_migration_issue](https://cloud.githubusercontent.com/assets/16081377/11680675/2e26f1fc-9e5a-11e5-989e-eabcae88cd1c.jpg)
  ![data_migration_issue](https://cloud.githubusercontent.com/assets/16081377/11680681/342cfec0-9e5a-11e5-9553-69cb8eb04022.jpg)

**Comment by quynhvv** [comment]
@salelsol:
Let's follow exactly steps in the guide of this tool at: https://github.com/ubertheme/magento2_data_migration

That issue, because you missing the step: http://i.imgur.com/5mW52kx.png

Also, please note that, we have released this tool as a Module for Magento 2 and you can download and try to free use it at:
https://github.com/ubertheme/module-ubdatamigration

Regards,
quynhvv

**Comment by salelsol** [comment]
- Hi in my case not works lasted upgraded:

Best Regards
Toni Mota

**Comment by salelsol** [comment]
- I´ve installed with composer, reindexed but there isn´t nothing to install in my root folder:
- I don´t know what to do know:

Best Regards
Toni Moya

**Comment by quynhvv** [comment]
@salelsol :That is a magento 2 module and you can find how to install that module at:
https://github.com/ubertheme/module-ubdatamigration

`composer require ubertheme/module-ubdatamigration`

`php -f PATH_YOUR_MAGENTO_2/bin/magento module:enable --clear-static-content Ubertheme_Ubdatamigration`

`php -f PATH_YOUR_MAGENTO_2/bin/magento setup:upgrade`
Regards,
quynhvv

**Comment by quynhvv** [comment]
@salelsol : Let's follow this https://github.com/ubertheme/module-ubdatamigration/releases/tag/v1.0.3

Regards,
quynhvv

**Comment by salelsol** [comment]
- Lasted upgrading customers migration it´s perfect with uber data migration extension .

Best regards
Toni Moya

**Comment by salelsol** [comment]
Migrating from local machine (all is fine) to cloud server I can´t install anything
![composer_install](https://cloud.githubusercontent.com/assets/16081377/11875268/30529720-a4e4-11e5-9afa-588bd3b4c71e.jpg)
 with composer, username and password not works like local macchine.

Best Regards
Toni Moya

**Comment by quynhvv** [comment]
@salelsol : That because you missing step as in guide at: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html
=> Let's do step as in guide to get username and password to continue.
=> That is a new step and only once for first update with composer in Magento 2 CE 2.0.0

**Comment by salelsol** [comment]
- I´ve reading and I´ve used same method in local machine and works fine using username and password from magento account Secure Keys, but now it´s imposible with SSH from cloud server.

Best Regards
Toni Moya

**Comment by quynhvv** [comment]
@salelsol : Maybe you have to generate a new key for the cloud server.
