### ISSUE TITLE
Store duplicate entry

### ISSUE THREAD

**Issue by rudik99** [ubertheme/magento2_data_migration#19]
Hi, 

I have a multistore setup, i keep getting the following error on the first step. I can solve it by deleting the entries from the database but it has implications later.

CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `store_website` (`sort_order`, `default_group_id`, `is_default`, `website_id`, `code`, `name`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)

This with the very latest version of the tool.

**Comment by quynhvv** [comment]
@rkhoury82 
Did you do exactly steps in the guide of this tool at https://github.com/ubertheme/magento2_data_migration ?

Please note that, the Magento 2 have to a fresh installation ( database without any data sample) before you start data migration with this tool.

Regards,
quynhvv

**Comment by rudik99** [comment]
@quynhvv yes exactly, I didn't install the sample data.
I installed a fresh magento2, I did login into the admin tho, but I don't think that matters.

**Comment by quynhvv** [comment]
@rkhoury82:

I think that issue because you have finished the step 1 'Migrate Settings' via tool of Magento at 
https://github.com/magento/data-migration-tool-ce/issues/16#issuecomment-164047618

After  'Migrate Settings' the websites and stores in magento 1 was migrated to your magento 2 database.

and then, you use our tool to continue data migration on this database.
In this case, you have to re-install a fresh Magento 2 or you can click to 'Reset All' button in our tool to reset the Magento 2 database come back a fresh database.
And then you can do data migration with our tool step by step.
Let's do it to solve your issue.

Regards,
quynhvv

**Comment by rudik99** [comment]
@quynhvv I'm doing these on seperate installs; both tools aren't working for me. 
I started using this one on a 100% fresh copy of Magento2 without using the magento/data-migration-tool-ce

**Comment by quynhvv** [comment]
@rkhoury82 
Does your Magento1 database working fine now?
Do you make re-index the data successfully on the Magento1?
Do you have re-try the data migration with this tool once more?
Regards,
quynhvv

**Comment by rudik99** [comment]
@quynhvv 
I can and did re-index magento1 successfully.
I have tried again and same problem still.
I got past the duplicate store by deleting the default store from the new magento 2 store.
Then I can't get past step 5, the next button doesn't work. The product actually migrated but the configurable product didn't keep the associated simple product attached, I saved all the attributes and re indexed. Haven't tried to trouble shoot any further yet

**Comment by quynhvv** [comment]
@rkhoury82 
Can you share me the screenshot to specify that you have re-index the data in Magento 1 successfully?
Regards,
quynhvv

**Comment by rudik99** [comment]
<img width="487" alt="screen shot 2015-12-30 at 7 02 12 pm" src="https://cloud.githubusercontent.com/assets/9780829/12047943/e288ba94-af27-11e5-9afa-f8803decbc15.png">

**Comment by rudik99** [comment]
Never got this to work, but others have, assume it was something to do with my database.
I ended up getting the Magento data migration tool to work instead.

**Comment by floramediaict** [comment]
Same issue:

DbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `store_website` (`sort_order`, `default_group_id`, `is_default`, `website_id`, `code`, `name`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5)

**Comment by UberthemeTeam** [comment]
Hi Floramediaict,

It's pity that we no longer maintain the old script of our migration tool here at Github. 

Please consider to take a look at our newer version UB Data MIgration Pro, as mentioned here: 
https://github.com/ubertheme/magento2_data_migration/issues/52#issuecomment-278958406

Sincerely,
Ubertheme team
