### ISSUE TITLE
not functioning with merchant beta 1.0

### ISSUE THREAD

**Issue by blint079** [ubertheme/magento2_data_migration#2]
sorry, I jumped the gun on opening an issue. Didn't read "Supported versions: Magento 2 version 0.74.0 beta x" Any timetable on a functioning migration tool for the merchant beta?

**Comment by quynhvv** [comment]
Hi blint079,
We have just release this tool to support Magento 2 version merchant beta 1.0.0
You can download it at https://github.com/ubertheme/magento2_data_migration/releases/tag/v0.1.18
Let's try use it and let me know how it goes.
