### ISSUE TITLE
No customer addresses?

### ISSUE THREAD

**Issue by jvukovich** [ubertheme/magento2_data_migration#20]
I've successfully executed steps 1 through 6. However, upon inspecting the database, I see that all customer_address_\* tables are empty. My source database has over 42,000 addresses. I didn't encounter any errors during the migration process. Don't see anything in the logs. Is customer address migration a known issue, or not done yet? Thanks!

Going from Magento 1.9.2.1 (all patches) to Magento-CE-2.0.0-2015-11-17-05-47-46.

**Comment by quynhvv** [comment]
@jvukovich,
Seem you are use old version of this tool. What version of this tool you are using?
Let's update to use the latest version of this tool to solve the issue as you said.
Regards,
quynhvv.

**Comment by jvukovich** [comment]
Damn. You know what? I may have been looking at old documentation and installed it using Composer. It got installed as a module under \vendor\ubertheme\module-ubdatamigration and \pub\ub-tool. Argh. I'll re-do everything per the instructions on the Github read me. Sorry about that. It took several days for the migration to run and now I can't remember what documentation I was following.

**Comment by jvukovich** [comment]
Ah ha! I was following THIS: https://github.com/ubertheme/module-ubdatamigration

I got it installed and kicked off the migration last Wednesday, Dec 9th and run everything through to today. Everything worked except the customer addresses.

So should I be using this source code (magento2_data_migration)? Or the Magento 2 module from link above (module-ubdatamigration)?

**Comment by quynhvv** [comment]
@jvukovich:

> https://github.com/ubertheme/module-ubdatamigration

Please follow to use the latest version of it (v 1.0.3), and tell me know how it goes.

Regards,
quynhvv

**Comment by jvukovich** [comment]
Okay, thanks. It'll take me a few days to re-run the migration. I'll get back to you. Thanks again!

**Comment by jvukovich** [comment]
I'm running customer import now, with 1.0.3, and I'm seeing the address tables getting populated. Thanks man!

**Comment by quynhvv** [comment]
@jvukovich : Yes, that is a good news. Let's tell me know when you finished the data migration.

**Comment by jvukovich** [comment]
Finished. It worked. Thanks!

**Comment by quynhvv** [comment]
@jvukovich : 
Yes, that is a good news. Can you tell me how many products, sales orders, customers...
in your working?

**Comment by jvukovich** [comment]
The first time I migrated all of our products, over 80,000, and it worked just fine. The second time I didn't migrate products (client wants to build catalog from scratch later).

Over 40,000 customers. Over 15,000 sales.

One thing is we have two custom fields for customers in Magento 1.x. I wasn't sure how to migrate them, so I thought I would figure it out later. One is a boolean: Purchased orders allowed? The second is a text field: Distributor Number.

We have one custom field for sales from OneStepCheckout: onestepcheckout_comments. We'll have to figure out how to migrate that later, too.

Thanks!
Jon

**Comment by quynhvv** [comment]
@jvukovich:
This tool only support to migrate the Product Attributes at this time.
We don't support to migrate the attributes added from any third-party extension, because that third-party extension wasn't available yet in your site with Magento 2 at this time. right?
Regards,
Mall.

**Comment by jvukovich** [comment]
The customer fields are ones we added ourselves. The other is from an extension, yes. I can figure out how to migrate them on my own. Thanks!
