### ISSUE TITLE
Step7 :Property "Mage2SalesOrder.gift_message_id" is not defined.

### ISSUE THREAD

**Issue by zexperto** [ubertheme/magento2_data_migration#25]
I have this exception 
Property "Mage2SalesOrder.gift_message_id" is not defined.
![image](https://cloud.githubusercontent.com/assets/2926032/12578050/2b69271c-c427-11e5-9838-7164ba56d17c.png)

![image](https://cloud.githubusercontent.com/assets/2926032/12578064/385ce6a2-c427-11e5-8cc5-c6b258eaf915.png)
![image](https://cloud.githubusercontent.com/assets/2926032/12578073/3f478b02-c427-11e5-9de7-3f55e8fb69e2.png)

**Comment by quynhvv** [comment]
@zexperto 
That because your Magento2 has not yet install the gift message module.
Let's press reset button and you can re-start data migration in this step.
Regards,
quynhvv.

**Comment by zexperto** [comment]
Thank you for quick reply , and thank you also for this great tool

**Comment by quynhvv** [comment]
@zexperto 
Thanks for your working around with this tool.
Can you share me know, how many data objects in your working?
Categories..?
Products....?
...
Regards,
quynhvv
