### ISSUE TITLE
Migration in hanging on Step2

### ISSUE THREAD

**Issue by derhelle** [ubertheme/magento2_data_migration#3]
Hi,
migration is hanging on Step 2. Wait for 30min...but nothing happend.

OS: Ubuntu 14.04
Old Magento: 1.9.1
New Magento: Magento ver. 1.0.0-beta

regards Helle

![migrat](https://cloud.githubusercontent.com/assets/13695179/9147262/ed639f54-3d64-11e5-8fb1-6025e00b8f29.jpg)

**Comment by derhelle** [comment]
Have still the same problem......

**Comment by quynhvv** [comment]
Hi derhelle,
We have just released this tool to support Magento 2 Merchant beta 1.0.0
To solve your issues, you can download the latest version of this tool at https://github.com/ubertheme/magento2_data_migration/releases/tag/v0.1.18

Let's do it and contact me if you need further assistance!

**Comment by samek** [comment]
It's the same with v0.1.18 for me. 
Also if you look at the network console, nothing even gets called when you press start.

**Comment by quynhvv** [comment]
Hi samek,
Let's provide me some screenshot about your working to specify the Magento versions...
Or you can add my Skype and we will working together to see the issues via Team viewer?
My SkypeID: quynh.vv

Regrads,
quynhvv

**Comment by quynhvv** [comment]
Hi samek,
We have detected the issue as you said and see that it only appear in Google Chrome Browser.
This is a issue of Java script and we will fix this at next release for this tool.
Now, you can try this tool with Firefox browser to migrate your data.
Thanks for your comment!

Regards,
quynhvv

**Comment by quynhvv** [comment]
Hi Hi samek,
To solve the issue with Google Chrome browser, you can do:
Download the js file https://github.com/ubertheme/magento2_data_migration/blob/master/js/script.js
and replace it to file at js/script.js in folder of the tool you have downloaded.

Let's do it and contact me if you need further help.

Regards,
quynhvv

**Comment by samek** [comment]
Looks very promising. 2900 out of 16000 products already imported. 
For now it works like a charm.

**Comment by quynhvv** [comment]
Yes, Let's me know when it finished.
Regards,
quynhvv

**Comment by samek** [comment]
Ok, 
All products are in, but it seams that something timed out in browser and It's still saying that step5 is not done yet. 
Is there a way to say that the step has finished ?

**Comment by quynhvv** [comment]
In your case, let's re-config the PHP and up the max_execution_time setting. And restart the tool with step 5.

Also, you can make reset a step manual, for example step 5 by url: http://URL_TO_YOUR_TOOL/migrate/reset/step/5

You shouldn't set a step to finished manual. It should update auto by application after everything for a step was done.

Regards,
Mall.

**Comment by samek** [comment]
It worked. I just had to refresh the page. 
Everything was imported.. GREAT.

**Comment by quynhvv** [comment]
Hi samek,
That is a good news!
Let's contact me if you need further help.
Regards,
quynhvv

**Comment by adam-inco** [comment]
Hello, I have now got to importing products but get errors on cataloginventory_stock_status & catalog_product_entity about duplicated entries, I delete the duplicates from the database but they come back each time I try to import.

CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-1-1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `cataloginventory_stock_status` (`qty`, `product_id`, `website_id`, `stock_id`, `stock_status`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4) 

any suggestions

Kind Regards
Adam

**Comment by quynhvv** [comment]
@adamw1987:
What versions of Magento1 and Magento2 you are working?
Please note that, your database working fine with Magento1 and the Magento 2 with a fress database (database after installation)

Also, you can make reset a step manual, for example step 5 by url: http://URL_TO_YOUR_TOOL/migrate/reset/step/5

and restart the step after reset.

Regards,
Mall.

**Comment by adam-inco** [comment]
Hi thank you for your reply

I am using magento 1.9.2

I have reset the the steps, and retired with just one website rather then 3, and this works so it seems to have an issue with multiple websites trying to import the same products multiple times

Kind Regards
Adam Watts

**Comment by quynhvv** [comment]
Hi adamw1987,

Yes, that is a good news.
Please note that, you can only make once import from Magento 1 -> Magento 2
for each step.
If you want to re-import on one step, the first you have to reset that step.

Regards,
quynhvv

On Wed, Oct 14, 2015 at 4:05 PM, adamw1987 notifications@github.com wrote:

> Hi thank you for your reply
> 
> I am using magento 1.9.2
> 
> I have reset the the steps, and retired with just one website rather then
> 3, and this works so it seems to have an issue with multiple websites
> trying to import the same products multiple times
> 
> Kind Regards
> Adam Watts
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/3#issuecomment-147983895
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by adam-inco** [comment]
Hi yeah, the issue I had was if I select 

Website 1, Website 2 & Website 3 on step 2, then step 5 errors when trying to import the products

Kind Regards
Adam Watts

**Comment by quynhvv** [comment]
Hi adamw1987,

We have tested this tool with multiple websites and stores and it's working
fine.
What version of this tool and Magento2 in your working?

Also, can you share me the file.zip of your Magento1 database?
I need to closer look to detect the issue as you said.

Thanks!

On Wed, Oct 14, 2015 at 4:14 PM, adamw1987 notifications@github.com wrote:

> Hi yeah, the issue I had was if I select
> 
> Website 1, Website 2 & Website 3 on step 2, then step 5 errors when trying
> to import the products
> 
> Kind Regards
> Adam Watts
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/3#issuecomment-147985600
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vikramacharya** [comment]
Hi,

I am using the latest version of ur migration tool. My older magento version is 1.7. 
While importing the product we are getting this error:
Property "Mage2CatalogProductEntityMediaGallery.entity_id" is not defined.

When I try to reset the step using URL ... migration//reset/step/5 I am getting 404 error.
![reset issue](https://cloud.githubusercontent.com/assets/1625240/10506110/05109eba-7332-11e5-9e8f-d219db83b492.png)

Can you please let me know what may be wrong in this case?

Thanks

**Comment by quynhvv** [comment]
Hi, to reset the Step 5 you can use the url:
http://your_tool_folder/index.php/migrate/reset/step/5

Regards,
quynhvv

On Thu, Oct 15, 2015 at 1:18 PM, Vikram Acharya notifications@github.com
wrote:

> Hi,
> 
> I am using the latest version of ur migration tool. My older magento
> version is 1.7.
> While importing the product we are getting this error:
> Property "Mage2CatalogProductEntityMediaGallery.entity_id" is not defined.
> 
> When I try to reset the step using URL ... migration//reset/step/5 I am
> getting 404 error.
> [image: reset issue]
> https://cloud.githubusercontent.com/assets/1625240/10506110/05109eba-7332-11e5-9e8f-d219db83b492.png
> 
> Can you please let me know what may be wrong in this case?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/3#issuecomment-148292638
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vikramacharya** [comment]
Hey,

I have followed the same url. But it is giving 404.

**Comment by quynhvv** [comment]
To reset the Step 5 you can use the url:

http://your_tool_folder/index.php/migrate/reset/step/5

Can you share me any screenshots about your working?

Please have a look again and re-try.

On Thu, Oct 15, 2015 at 1:54 PM, Vikram Acharya notifications@github.com
wrote:

> Hey,
> 
> I have followed the same url. But it is giving 404.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/3#issuecomment-148298099
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by quynhvv** [comment]
@guys: I would like to announcement that, we have just released two Magento modules for this:
- Once for Magento CE 1.x: https://docs.google.com/document/d/1FmJfDIm8u09m8T9jcCL38t3vRxcKbS7DMltaA2WFUI8/edit#heading=h.75wvj9m0za9x
- Once for Magento CE  2.0.0:
  https://github.com/ubertheme/module-ubdatamigration

You can chose 1 or 2 is optional.
Regards,
quynhvv
