### ISSUE TITLE
Can't find sales_order_status_label table with prefix

### ISSUE THREAD

**Issue by davideperrotta** [ubertheme/magento2_data_migration#40]
If you are using a prefix on table for Magento2 DB, this tool gives you an error on "Sales Products" on 7th step because can't find **sales_order_status_label** table in database. To solve this you can create the table without prefix and go next, when the step is complete you can rename the table (deleting previous existing table with prefix) or migrate these datas manually.

**Comment by quynhvv** [comment]
@davideperrotta 
Thanks you working around on this tool. 
To solve this issue, you also can open the file at path: `protected/models/db/mage2/Mage2SalesOrderStatusLabelPeer.php`
and find to the code line: `return 'sales_order_status_label';`
and replace it by code line: `return '{{sales_order_status_label}}';`
We are missing this in this model class.
For further questions, you can submit here: https://www.ubertheme.com/questions/
Regards,
Mall.
