### ISSUE TITLE
error importing categories. script timeout with 10000 cats.

### ISSUE THREAD

**Issue by price2b** [ubertheme/magento2_data_migration#5]
just a comment, I tried to migrate from magento 1 to 2 using Magento2_data_migration, everything worked perfect but despite I modified php.ini max-execution categories (aprox 10.000) gave error when importing. i dont know if the tool have any log but if it has, let me know and I can upload it here. brgds!

**Comment by quynhvv** [comment]
Hi price2b,
Can you provide me any screenshots about steps in your working?
The log of tool only take errors, and you can find it in folder at /protected/runtime/
Regards,
Mall.

**Comment by price2b** [comment]
yes of course, thank you for your prompt answer.. runtime application.log display the following information:

2015/11/15 06:51:08 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[70100]: <<Unknown error>>: 1317 Query execution was interrupted. The SQL statement executed was: SELECT entity_type_id FROM eav_entity_type WHERE entity_type_code = 'catalog_category'.
2015/11/15 06:51:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[70100]: <<Unknown error>>: 1317 Query execution was interrupted. The SQL statement executed was: SELECT entity_type_id FROM eav_entity_type WHERE entity_type_code = 'catalog_category'' in C:\Zend\Apache2\htdocs\migrate-data-tool\yii\db\CDbCommand.php:543
Stack trace:
#0 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\db\CDbCommand.php(433): CDbCommand->queryInternal('fetchColumn', 0, Array)
#1 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(248): CDbCommand->queryScalar()
#2 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(231): MigrateSteps::getMage1EntityTypeId('catalog_categor...')
#3 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(213): MigrateSteps::getMage1CategoryName('9505')
#4 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('9486')
#5 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('9466')
#6 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('8689')
#7 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('8074')
#8 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('4')
#9 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\views\migrate\step4.php(38): MigrateSteps::getMage1CategoryTree('2')
#10 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CBaseController.php(126): require('C:\Zend\Apache2...')
#11 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\Zend\Apache2...', Array, true)
#12 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(869): CBaseController->renderFile('C:\Zend\Apache2...', Array, true)
#13 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(782): CController->renderPartial('step4', Array, true)
#14 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\controllers\MigrateController.php(919): CController->render('step4', Array)
#15 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\actions\CInlineAction.php(49): MigrateController->actionStep4()
#16 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#18 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CWebApplication.php(282): CController->run('step4')
#20 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CWebApplication.php(141): CWebApplication->runController('migrate/step4')
#21 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\base\CApplication.php(184): CWebApplication->processRequest()
#22 C:\Zend\Apache2\htdocs\migrate-data-tool\index.php(13): CApplication->run()
#23 {main}

## REQUEST_URI=/migrate-data-tool/index.php/migrate/step4

**Comment by quynhvv** [comment]
Hi price2b,
What versions of Magento1 and Magento 2 in your working?
What version of the tool you are using?
Can you share me the file.zip of your Magento1 database?

Regards,
Mall.

**Comment by price2b** [comment]
a. magento 1.9.2
b. magento2_data_migration-0.1.19
c. I have a lot of proprietary info, can I send you the categories information in csv file if its ok?

**Comment by quynhvv** [comment]
Hi price2b,

CSV file can't help for this case.
I have tuning and make some cache process to support a large data.
Let download the config file at https://github.com/ubertheme/magento2_data_migration/blob/master/protected/config/main.php
and replace it to source code of this tool in your web root at /protected/config/main.php
and download the file at https://github.com/ubertheme/magento2_data_migration/blob/master/protected/models/MigrateSteps.php
and replace it to source code of this tool in your web root at /protected/models/MigrateSteps.php
and fresh F5 to re-start this tool with step 4

Do it and let's me know how it goes.

**Comment by price2b** [comment]
thank you for your update. I put those files but same timeout happens.

new log:

09:47:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[70100]: <<Unknown error>>: 1317 Query execution was interrupted. The SQL statement executed was: SELECT \* FROM `catalog_category_entity` `t` WHERE parent_id = 10753' in C:\Zend\Apache2\htdocs\migrate-data-tool\yii\db\CDbCommand.php:543
Stack trace:
#0 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\db\ar\CActiveRecord.php(1356): CDbCommand->queryAll()
#2 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(208): CActiveRecord->findAll('parent_id = 107...')
#4 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('10753')
#5 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('10730')
#6 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('10548')
#7 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\models\MigrateSteps.php(215): MigrateSteps::getMage1CategoryTree('6')
#8 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\views\migrate\step4.php(38): MigrateSteps::getMage1CategoryTree('2')
#9 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CBaseController.php(126): require('C:\Zend\Apache2...')
#10 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CBaseController.php(95): CBaseController->renderInternal('C:\Zend\Apache2...', Array, true)
#11 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(869): CBaseController->renderFile('C:\Zend\Apache2...', Array, true)
#12 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(782): CController->renderPartial('step4', Array, true)
#13 C:\Zend\Apache2\htdocs\migrate-data-tool\protected\controllers\MigrateController.php(919): CController->render('step4', Array)
#14 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\actions\CInlineAction.php(49): MigrateController->actionStep4()
#15 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CWebApplication.php(282): CController->run('step4')
#19 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\web\CWebApplication.php(141): CWebApplication->runController('migrate/step4')
#20 C:\Zend\Apache2\htdocs\migrate-data-tool\yii\base\CApplication.php(184): CWebApplication->processRequest()
#21 C:\Zend\Apache2\htdocs\migrate-data-tool\index.php(13): CApplication->run()
#22 {main}

## REQUEST_URI=/migrate-data-tool/index.php/migrate/step4

**Comment by quynhvv** [comment]
That because you have too much of categories in your working.
Performance in your local web server can't finish this task.
For this case, you should run this tool in a machine with high performance, you should move to run migration in a VPS ...

Have a look and contact me if you need further assistance.

**Comment by price2b** [comment]
Perfect. I Will try that option.  Thank you so much for your time and
support.
