### ISSUE TITLE
 Exist customer can't login after migration

### ISSUE THREAD

**Issue by ashvinim0003** [ubertheme/magento2_data_migration#55]
**Preconditions**

    Apache
    PHP 5.6

**Steps to reproduce**

    Data migration from magento 1.9.x to magento 2.1.3
    Got error while importing customers ( error - Mage2CustomerEnttityText - Value cannot be blank)
    All step completed

**Expected result**

    Sales , customer and products all data migrated to magento 2

**Actual result**

    All customer showing in admin after re-index.
    Exist customer can't login
    New customer login is working fine.
    Found following error while exporting data from all customer section

**Comment by UberthemeTeam** [comment]
Hi there, 

It's pity we no longer maintain the old script distributed here on Github, as its codebase was outdated. We've replaced with a newer version [here](https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/). 

Many users have been using our new migration tool without issues as you mentioned. A few to name [here](https://www.ubertheme.com/magento2/case-study-winetasting-migrate-customer-entities-to-magento-2/) and [here](https://www.ubertheme.com/magento2/data-migration-230000-products).

Thanks for your understanding. 

Regards,
Ubertheme team

**Comment by ashvinim0003** [comment]
Solved 
Thanks
