### ISSUE TITLE
Issue on Product migration

### ISSUE THREAD

**Issue by vickkeane** [ubertheme/magento2_data_migration#6]
Here i get the error to the Migrate Product step . help me Asap

CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `mg_catalog_product_entity` (`attribute_set_id`, `type_id`, `has_options`, `required_options`, `entity_id`, `sku`, `created_at`, `updated_at`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7)

**Comment by quynhvv** [comment]
Hi vickkeane,

What versions Magento 1 and Magento 2 in your working?
What version of the migrate tool you are using?

Regards,
Mall.

On Sat, Nov 21, 2015 at 2:13 PM, vickkeane notifications@github.com wrote:

> Here i get the error to the Migrate Product step . help me Asap
> 
> CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity
> constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL
> statement executed was: INSERT INTO mg_catalog_product_entity (
> attribute_set_id, type_id, has_options, required_options, entity_id, sku,
> created_at, updated_at) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6,
> :yp7)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6.

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by asad-developers** [comment]
Hi,
      I have followed the steps mentioned and i am really happy it did work as it should be. However after finishing this i have only got 1 problem. I am unable to reindex data on windows. I am trying to access shell as per description but i am unable to locate shell inside dev folder of my magento 2.0. I will highly appreciate your help. Thank you. 

Best Regards,
Asad

**Comment by asad-developers** [comment]
@vickkeane i think you should check the version of your magento installation first. From error you have mentioned it seems you are trying to migrate from different version than mentioned in settings on migration tool. Cheers!!

Best Regards,
Asad

**Comment by quynhvv** [comment]
@creativeitzone:
Please follow the guide of this tool at:
https://github.com/ubertheme/magento2_data_migration

Please note that:
_Important Note:_ If you are using _Magento 2 version 0.74.0 - beta 9 or
later_: To reindex all data, run following command line:
_php -f WEB_ROOT_PATH\your_magento2_folder\bin\magento indexer:reindex_

Have a look and let me know if you need further assistance!
Regards,
quynhvv

On Sun, Nov 22, 2015 at 5:51 PM, creativeitzone notifications@github.com
wrote:

> @vickkeane https://github.com/vickkeane i think you should check the
> version of your magento installation first. From error you have mentioned
> it seems you are trying to migrate from different version than mentioned in
> settings on migration tool. Cheers!!
> 
> Best Regards,
> Asad
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158745268
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by asad-developers** [comment]
Thanks for coming back to me. First of all i am very happy with all of your effort for data migration. I will see great work!! Secondly yes i am using Magento-CE-2.0.0 and i have tried already _php -f WEB_ROOT_PATH\your_magento2_folder\bin\magento indexer:reindex_ but unfortunately there was no any luck :( 

Best Regards,
Asad

**Comment by asad-developers** [comment]
I am sorry for creating a little bit confusion for you. Actually reindexing was done properly when i did use the same method you have mentioned above. Issue was with login to admin panel. When i am trying to logged in to the admin panel with my username and password i am getting this message "You did not sign in correctly or your account is temporarily disabled." I really apologize actually there i have opened a separate issue for that. Thanks you

Best Regards,
Asad

**Comment by quynhvv** [comment]
Hi Asad,
Did you don't see the "bin" folder in the Magento2 web root folder?
It is here: https://github.com/magento/magento2/tree/develop/bin
Let's open the Terminal window and make reindex the database of Magento2 by
command line as guide.
You can see more at my screenshot: http://i.imgur.com/ICvnBIC.png

Please have a look!

Regards,
quynhvv

On Sun, Nov 22, 2015 at 9:10 PM, Asad notifications@github.com wrote:

> Thanks for coming back to me. First of all i am very happy with all of
> your effort for data migration. I will see great work!! Secondly yes i am
> using Magento-CE-2.0.0 and i have tried already _php -f
> WEB_ROOT_PATH\your_magento2_folder\bin\magento indexer:reindex_ but
> unfortunately there was no any luck :(
> 
> Best Regards,
> Asad
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158762191
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by asad-developers** [comment]
No i can see bin as well. Indexing is proper and on frontend i can see my data. Only problem is with backend login. 
![image](https://cloud.githubusercontent.com/assets/6056696/11324464/d0774d9c-914b-11e5-8fd8-2b84164cf717.png)
I am using windows and i have attached screenshot above. And here is the screenshot for error i am getting below:
![image](https://cloud.githubusercontent.com/assets/6056696/11324476/16f02384-914c-11e5-879b-d9ab10aa888f.png)

Thank you

Best Regards,
Asad

**Comment by quynhvv** [comment]
Hi Asad,

The seem you are miss the password of admin credentials with Magento2.
I re-note that, the tool doesn't make change the admin credentials of
Magento 2.

For this case, you should use the 'Forgot your password?' provided by
Magento2.

Regards,
quynhvv.

On Sun, Nov 22, 2015 at 10:06 PM, Asad notifications@github.com wrote:

> No i can see bin as well. Indexing is proper and on frontend i can see my
> data. Only problem is with backend login.
> [image: image]
> https://cloud.githubusercontent.com/assets/6056696/11324464/d0774d9c-914b-11e5-8fd8-2b84164cf717.png
> I am using windows and i have attached screenshot above. And here is the
> screenshot for error i am getting below:
> [image: image]
> https://cloud.githubusercontent.com/assets/6056696/11324476/16f02384-914c-11e5-879b-d9ab10aa888f.png
> 
> Thank you
> 
> Best Regards,
> Asad
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158765493
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vickkeane** [comment]
@quynhvv 
@creativeitzone 
I am using 1.9.1.0 to magento2 full version .Migrating 2000 products and 50 categories .
Migration tool version 0.1.20
Thanks

**Comment by quynhvv** [comment]
@vickkeane: Good news! Thanks for your action ;)

**Comment by vickkeane** [comment]
@quynhvv  Thanks for your valuable response. How to solve the problem am trying out for past 2 days .
Thanks

**Comment by quynhvv** [comment]
@vickkeane:

The seem you have add some products to Magento 2 before you use this tool
to migrate data?

Please note that: The database of Magento 2 have to be a fress database
before you make migration data with this tool.

If yes, you can make reset the Migrate Product step (Step 5) by bellow URL:

http:///URL_TO_THIS_TOOL/migrate/reset/step/5/

And you can re-migrate in this step after reset.

Regards,
quynhvv

On Mon, Nov 23, 2015 at 3:32 PM, vickkeane notifications@github.com wrote:

> @quynhvv https://github.com/quynhvv Thanks for your valuable response.
> How to solve the problem am trying out for past 2 days .
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158876360
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vickkeane** [comment]
@quynhvv  yes of course i did this for more then 3 times .
Thanks

**Comment by quynhvv** [comment]
@vickkeane:
And you still get that errors with step5?
Does your magento1 website working fine? Did you have make re-index data
success in Magento1 website?

On Mon, Nov 23, 2015 at 3:47 PM, vickkeane notifications@github.com wrote:

> @quynhvv https://github.com/quynhvv yes of course i did this for more
> then 3 times .
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158878287
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vickkeane** [comment]
yes i get this same error even i reindex or reset all but i have not reindex magento 1 site . i do following only in magento2.
Thanks

**Comment by quynhvv** [comment]
@vickkeane:

Let's make re-index the data of Magento1 database and tell me how it goes?

On Mon, Nov 23, 2015 at 4:30 PM, vickkeane notifications@github.com wrote:

> yes i get this same error even i reindex or reset all but i have not
> reindex magento 1 site
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158886468
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by asad-developers** [comment]
@vickkeane  it can be a silly question but i just want to confirm have you installed magento 2 without sample products? And you are migrating from the version that you have mentioned in script?

**Comment by vickkeane** [comment]
@quynhvv  yes without sample data i installed magento2 .after reindex both versions and reset all using migration tool now gets error.

CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL statement executed was: INSERT INTO `mg_cataloginventory_stock_item` (`product_id`, `stock_id`, `min_qty`, `use_config_min_qty`,

**Comment by asad-developers** [comment]
@vickkeane are you using custom extensions for your website? or if you are using third part extensions can you please share?

**Comment by vickkeane** [comment]
yes using lot of version . sorry am having both site in localserver for migrate. partproductpdf ,Manadev wordpress integrations etc ..,

**Comment by quynhvv** [comment]
@vickkeane:

I thinks issue come from your database of Magento 1. Seem It contain a
duplicate data.
I want to see that, Your Magento 1 is working fine. Can you share me admin
credentials of that?

Can you share me the screenshots in your working?

On Mon, Nov 23, 2015 at 4:41 PM, vickkeane notifications@github.com wrote:

> @quynhvv https://github.com/quynhvv yes without sample data i installed
> magento2 .after reindex both versions and reset all using migration tool
> now gets error.
> 
> CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity
> constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'. The SQL
> statement executed was: INSERT INTO mg_cataloginventory_stock_item (
> product_id, stock_id, min_qty, use_config_min_qty,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158888781
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vickkeane** [comment]
Yes my magento 1 is working fine .Here i attached screenshot .
Thanks

![2mg](https://cloud.githubusercontent.com/assets/15953328/11333733/fb690ab8-91f5-11e5-8d2e-e1ba9fa75bc4.png)
![3mg](https://cloud.githubusercontent.com/assets/15953328/11333734/fb6a9b80-91f5-11e5-9ebb-77daa2700fd2.png)

**Comment by quynhvv** [comment]
@vickkeane:

I see a request re-index database in Magento 1 site:
http://i.imgur.com/9tlbFu1.png
Let's make re-index as suggest and provide me the screenshot about your
magento 1 site and specify the Magento 1 version.

Also, did you run manual to reset step 5 with URL as i suggested?: http://
/URL_TO_THIS_TOOL/migrate/reset/step/5/

I want to see that, you have do it. Let's capture the screenshot after you
make reset on setp5 succesfully.

On Mon, Nov 23, 2015 at 4:52 PM, vickkeane notifications@github.com wrote:

> Yes my magento 1 is working fine .Here i attached screenshot .
> Thanks
> [image: 1mg]
> https://cloud.githubusercontent.com/assets/15953328/11333732/fb6361f8-91f5-11e5-9aca-6933462aae22.png
> [image: 2mg]
> https://cloud.githubusercontent.com/assets/15953328/11333733/fb690ab8-91f5-11e5-8d2e-e1ba9fa75bc4.png
> [image: 3mg]
> https://cloud.githubusercontent.com/assets/15953328/11333734/fb6a9b80-91f5-11e5-9ebb-77daa2700fd2.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158890807
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vickkeane** [comment]
@quynhvv  if i try to reindex url rewrite management not reindexing and also i reset the 5th step.
Once again Thanks for your valuable time and response.

![4mg](https://cloud.githubusercontent.com/assets/15953328/11334129/fa318ad2-91f8-11e5-9e8a-dba4678c76b3.png)
![5mg](https://cloud.githubusercontent.com/assets/15953328/11334130/fa37675e-91f8-11e5-9f2d-babd16d666cf.png)

**Comment by quynhvv** [comment]
@vickkeane:

_https://ci6.googleusercontent.com/proxy/TcyMuBxrQIlvsfHRr2TxmFSD7YMqHQWD_lUlQwEh2nGhFiYgbX2f1A1IUxkc-Aqu5I_PiOFFWpki9KKTq0ZQatWxgW7QgbRqNoK1Ur4lTMxFQbIXcW5ufGCLv-xGL5WW9freeZkexMTeI1phPBRFKuHUulwHAF7-_4HR=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/15953328/11334129/fa318ad2-91f8-11e5-9e8a-dba4678c76b3.png
https://ci6.googleusercontent.com/proxy/TcyMuBxrQIlvsfHRr2TxmFSD7YMqHQWD_lUlQwEh2nGhFiYgbX2f1A1IUxkc-Aqu5I_PiOFFWpki9KKTq0ZQatWxgW7QgbRqNoK1Ur4lTMxFQbIXcW5ufGCLv-xGL5WW9freeZkexMTeI1phPBRFKuHUulwHAF7-_4HR=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/15953328/11334129/fa318ad2-91f8-11e5-9e8a-dba4678c76b3.png_
The screenshot specify that, you database has a issue in Magento1, and that
is a reason you have take error in migrate tool.

Let's solve the issue in Magento1 database, and re-try with this tool.

Thanks.

On Mon, Nov 23, 2015 at 5:14 PM, vickkeane notifications@github.com wrote:

> @quynhvv https://github.com/quynhvv if i try to reindex url rewrite
> management not reindexing and also i reset the 5th step.
> Once again Thanks for your valuable time and response.
> 
> [image: 4mg]
> https://cloud.githubusercontent.com/assets/15953328/11334129/fa318ad2-91f8-11e5-9e8a-dba4678c76b3.png
> [image: 5mg]
> https://cloud.githubusercontent.com/assets/15953328/11334130/fa37675e-91f8-11e5-9f2d-babd16d666cf.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158896090
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by vickkeane** [comment]
@quynhvv  Let me do. Thanks dude .

**Comment by quynhvv** [comment]
@vickkeane:

Can you close this issue?
Let's contact me if you get any issues after come back with this tool.

Thanks.

On Mon, Nov 23, 2015 at 5:21 PM, vickkeane notifications@github.com wrote:

> @quynhvv https://github.com/quynhvv Let me do. Thanks dude .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/6#issuecomment-158897168
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by quynhvv** [comment]
@guys: I would like to announcement that, we have just released two Magento modules for this:
- Once for Magento CE 1.x: https://docs.google.com/document/d/1FmJfDIm8u09m8T9jcCL38t3vRxcKbS7DMltaA2WFUI8/edit#heading=h.75wvj9m0za9x
- Once for Magento CE  2.0.0:
  https://github.com/ubertheme/module-ubdatamigration

You can chose 1 or 2 is optional.
Regards,
quynhvv
