### ISSUE TITLE
Unable to re-index data after migration

### ISSUE THREAD

**Issue by asad-developers** [ubertheme/magento2_data_migration#7]
Hi,
     I have migrated my data fom magento 1.7 to 2.0 successfully. However when i am trying to login to my admin panel with my username and password i am getting this message "You did not sign in correctly or your account is temporarily disabled." Is there something wrong with account migration? Any idea why its been happening?

**Comment by quynhvv** [comment]
Hi Asad,

The migration tool doesn't make change the admin credentials of your site
in Magento1 and Magento 2.

Please have a look.

On Sun, Nov 22, 2015 at 7:30 PM, Asad notifications@github.com wrote:

> Hi,
> I have migrated my data fom magento 1.7 to 2.0 successfully. However when
> i am trying to login to my admin panel with my username and password i am
> getting this message "You did not sign in correctly or your account is
> temporarily disabled." Is there something wrong with account migration? Any
> idea why its been happening?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/7.

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002
