### ISSUE TITLE
Product migrate

### ISSUE THREAD

**Issue by quienti** [ubertheme/magento2_data_migration#9]
Have you an idea for this problem ?

Magento 1.9.2.2 to Magento 2.0.0 with mgrate-data-tool v0.1.20

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11374723/c691c298-92d7-11e5-907f-f03d22748cd7.png)

Thanks

**Comment by quynhvv** [comment]
Hi quienti,
Did you do exactly steps in the guide of this tool?https://github.com/ubertheme/magento2_data_migration/blob/master/README.md

For this case, you can make reset this step by URL:
http://URL_TO_THIS_TOOL/migrate/reset/step/5
and you can re-migrate this step after reset.

Let's do it and tell me know how it goes.
Regards,
quynhvv

**Comment by quienti** [comment]
Hi

I followed your guide step by step and I have reset my step 5.
But I have same issue.

**Comment by philipvandebriel** [comment]
Hi , 
Get the same error in the same table and we have 5000 categories and can upload max 1001 categories. Can you help us ?

Best Regards,
Philip

**Comment by quynhvv** [comment]
Hi guys: 
That issue because, your magento 1 databse the are a wrong value in `cataloginventory_stock_item` table.
Did your Magento 1 working fine now?
Can you make re-index successfully the database in back-end of Magento 1 website now?

To solve this issue, you can do steps bellow:

Step 1: 
Down load this PHP file: `https://github.com/ubertheme/magento2_data_migration/blob/master/protected/controllers/MigrateController.php`
and replace it to path in your working: `/protected/controllers/MigrateController.php`

Step 2: Make manual reset the step 5 by URL: `http://URL_TO_THIS_TOOL/migrate/reset/step/5`

Step 3: Re-start data migration on this step and next steps.

Do it and let's me know how it goes.
Regards,
quynhvv

**Comment by quienti** [comment]
Thanks, I will try now

**Comment by quienti** [comment]
Actually, my step 5 is very long because I have more 1 000 products...

But I check my database and in my table "cataloginventory_stock_item", all items are duplicated.

You can see my screenshoot here

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11419848/6fc98b68-942a-11e5-9d35-17423f4adcc5.jpg)

**Comment by quynhvv** [comment]
@quienti:
That because you have multiple websites in the Magento 1 database.
Did you see the new field named 'website_id' in cataloginventory_stock_item table in magento 2 database? This is a reason ;)
http://i.imgur.com/Z9l1RvX.png
Let's do steps as i suggested to solve the issue in your working.
Regards,
quynhvv

**Comment by philipvandebriel** [comment]
Hi,
After reindex the sqlstate 23000 is gone. But can't upload all the categories max 1001 categories then go to the next step ( no error ) . I change also the new migrate controller file. Do you have a solution for the categories ?

Thanks,
Philip

**Comment by philipvandebriel** [comment]
MAX 1001 categories , i have more then 5000 categories

![schermafdruk 2015-11-26 11 47 17](https://cloud.githubusercontent.com/assets/15958461/11421218/b7b73bd8-9433-11e5-8fab-73416ebf866e.png)

**Comment by quynhvv** [comment]
@philipvandebriel:
Did you check the total of categories migrated in database of Magento2? How many is it?
Can you share me the screenshot of list categories in magento 1 website?
Let's capture for me full of screenshot in step 4.

Regards,
quynhvv

**Comment by philipvandebriel** [comment]
Hi,
Magento 1
![schermafdruk 2015-11-26 11 57 52](https://cloud.githubusercontent.com/assets/15958461/11421426/010ba8e0-9435-11e5-83f4-37047c493566.png)

and magento 2

![schermafdruk 2015-11-26 11 57 34](https://cloud.githubusercontent.com/assets/15958461/11421434/0f80cfa4-9435-11e5-8a5c-c2f148ad0f68.png)

**Comment by philipvandebriel** [comment]
Before i start the step4 all categories are checked, after only the first 1001 have a green check.

**Comment by philipvandebriel** [comment]
Ok maybe i need to change this max_input_vars in php.ini this is now 1000

**Comment by quienti** [comment]
> That because you have multiple websites in the Magento 1 database.
> Did you see the new field named 'website_id' in cataloginventory_stock_item table in magento 2 
> database? This is a reason ;)

Yes, I'm stupid !

Your update work fine ! All products are migrated
But now, I have an other problem with my customer

![capture](https://cloud.githubusercontent.com/assets/7326954/11423095/c2c4b6d2-9441-11e5-8e6c-4a0b5795a73d.PNG)

I have 2 customers groups, and this problem occurs on the seconds groups

And my website in Magento 1 work fine with no problem !

(Sorry for my english, I'm French)

**Comment by quienti** [comment]
Ok, I have found the problem

Magento 2 have already 4 customers groups, and my database have a customers groups with same id !

So, I have change a customer groups id on Magento 2 and it's works

**Comment by quienti** [comment]
After few hours, another problem, not exacty same here : https://github.com/ubertheme/magento2_data_migration/issues/11

But, I have not all my sales !

Any idea ?

![capture2](https://cloud.githubusercontent.com/assets/7326954/11427880/bbbab98e-9466-11e5-9ad3-b7d67c26cd3f.PNG)

**Comment by philipvandebriel** [comment]
Hi Quienti,

you need to change the max_input_vars in php.ini  max_input_vars = 10000 

I had the same problem with our categories

**Comment by quynhvv** [comment]
@philipvandebriel:

That because there are too much of categories levels in your categories tree in Magento1 database.
I have tuning to support your case with 5000+ categories. To solve the issue as you said, let's do steps as bellow:

Step 1: Make manual reset the step 4 by URL: `http://URL_TO_THIS_TOOL/migrate/reset/step/5`
Step 2: Download the file at `https://github.com/ubertheme/magento2_data_migration/blob/master/protected/views/migrate/step4.php`
and replace it to path in your working: `/protected/views/migrate/step4.php`
Step 3: Download the file at: `https://github.com/ubertheme/magento2_data_migration/blob/master/protected/controllers/MigrateController.php`
and replace it to path in your working: `/protected/controllers/MigrateController.php`

Step 4: Restart with data migration on this step. See more: 
![step 4 note](http://i.imgur.com/98XclXm.png)

### Note: Don't miss re-settings the max_execution_time and max_input_time in your web server before re-start with step 4.

Let's do it and tell me know how its goes.

**Comment by philipvandebriel** [comment]
After i change max_input_vars = 10000 then the categories are ok, now i am busy with our 7000 products.

**Comment by quynhvv** [comment]
@philipvandebriel : Great, Let's tell me know after you finished. ;)

On Fri, Nov 27, 2015 at 12:08 AM, philipvandebriel <notifications@github.com

> wrote:
> 
> After i change max_input_vars = 10000 then the categories are ok, now i am
> busy with our 7000 products.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/9#issuecomment-159961483
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by philipvandebriel** [comment]
also change this after 

<IfModule mod_fcgid.c>
AddHandler fcgid-script .fcgi
IdleTimeout 7200
BusyTimeout 7200
ProcessLifeTime 7200
IPCConnectTimeout 7200
IPCCommTimeout 7200
FcgidIOTimeout   7200
</IfModule>

max_input_vars = 10000
memory_limit = 2048M
max_execution_time = 18000

**Comment by quienti** [comment]
> you need to change the max_input_vars in php.ini max_input_vars = 10000
> 
> I had the same problem with our categories

So, just change this value can work ?
Just restart all migration with many hours, I'm very happy !! ^^

**Comment by quynhvv** [comment]
@quienti: Yes, let's do it and tell me know how it goes ;)

**Comment by quienti** [comment]
Ok, I launch that, but a result in few hours ^^

**Comment by philipvandebriel** [comment]
Products migrate;
Error mod_fcgid: read data timeout in 7200 seconds stop after 6700 products

so i change now ; and start again
IdleTimeout 15000
BusyTimeout 15000
ProcessLifeTime 15000
IPCConnectTimeout 15000
IPCCommTimeout 15000
FcgidIOTimeout 15000

**Comment by philipvandebriel** [comment]
because i have 7000 products, until now this migrate module work normally for me ( so only change the settings in the server)

**Comment by philipvandebriel** [comment]
Hi,
Migrate products and customers ok.

Now i have this error; i change from memory 2G to 8G same error after 1041 sales orders
![schermafdruk 2015-11-27 08 07 04](https://cloud.githubusercontent.com/assets/15958461/11435750/39f008a0-94de-11e5-856f-34a32d051be0.png)

Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 88 bytes) in /var/www/clients/client1/web2/web/migrate-data-tool/yii/db/CDbCommand.php on line 518

![schermafdruk 2015-11-27 08 10 31](https://cloud.githubusercontent.com/assets/15958461/11435773/65f4dd04-94de-11e5-9250-d2252a5b5500.png)

**Comment by quienti** [comment]
Hi!

Like yesterday, I got a problem with my migration

https://cloud.githubusercontent.com/assets/7326954/11427880/bbbab98e-9466-11e5-9ad3-b7d67c26cd3f.PNG

All my sales are not migrated !

For example, in my database, my firt sale id is 687, but in magento 1, is id 1

**Comment by philipvandebriel** [comment]
Hi,
Did you check your php info ;
![schermafdruk 2015-11-27 09 10 49](https://cloud.githubusercontent.com/assets/15958461/11436643/e360bf08-94e6-11e5-9ee4-349aa272d5a7.png)

**Comment by quienti** [comment]
Yes

![sans titre 1](https://cloud.githubusercontent.com/assets/7326954/11436704/767f8be8-94e7-11e5-9c84-a5e52a7ed909.jpg)

**Comment by philipvandebriel** [comment]
Hi,
Did you check your error.log from the server ?
Before i get this with my categories ;
mod_fcgid: stderr: PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini

**Comment by philipvandebriel** [comment]
Maybe you need to reset step 7 and check the sales ID if it is zero after reset

http://URL_TO_THIS_TOOL/migrate/reset/step/7

**Comment by philipvandebriel** [comment]
Hi,
After reset step 7 i get this in my database ;
![schermafdruk 2015-11-27 09 27 18](https://cloud.githubusercontent.com/assets/15958461/11436909/5d02c1ba-94e9-11e5-9d25-a730bdeb6b01.png)

and auto increment start on 1

![schermafdruk 2015-11-27 09 29 11](https://cloud.githubusercontent.com/assets/15958461/11436922/70a0007a-94e9-11e5-82a1-9a910eedd2d3.png)

**Comment by quienti** [comment]
I have no error in error.log, I reset all database in magento 2 and restart all migration

**Comment by quynhvv** [comment]
@quienti :
Before you restart the data migration, you should follow this: https://github.com/ubertheme/magento2_data_migration/issues/11

Regards,
quynhvv

**Comment by quienti** [comment]
Yes, I see that !

I have get your last master and I had add this fix too

**Comment by philipvandebriel** [comment]
Hi Quynhvv,

I have a memory problem in step 7, change from 2G to 8G but nothing change ;
Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 88 bytes) in /var/www/clients/client1/web2/web/migrate-data-tool/yii/db/CDbCommand.php on line 518

**Comment by quynhvv** [comment]
@philipvandebriel:

Did you try with this settings?

```
//memory_limit
@ini_set('memory_limit', '-1');

```

On Fri, Nov 27, 2015 at 3:44 PM, philipvandebriel notifications@github.com
wrote:

> Hi Quynhvv,
> 
> I have a memory problem in step 7, change from 2G to 8G but nothing change
> ;
> Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to
> allocate 88 bytes) in
> /var/www/clients/client1/web2/web/migrate-data-tool/yii/db/CDbCommand.php
> on line 518
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ubertheme/magento2_data_migration/issues/9#issuecomment-160071970
> .

## 

Best regards, Quynh Vu Van.

## http://www.magentocommerce.com/certification/directory/dev/1639183/

Skype:  quynh.vv
Mobile:  098 525 2002

**Comment by philipvandebriel** [comment]
Hi,
Ok i will try with -1

**Comment by philipvandebriel** [comment]
Hi Quynhvv,
Yes there is a problem not all my sales are migrated, same problem as quienti . Busy with sales quote now , memory is stable (no memory errors until now)

**Comment by philipvandebriel** [comment]
Start again with step 7 ;
replace the block will work.
foreach ($sales_order2->attributes as $key => $value){
                                    if (isset($sales_order->$key)){
                                        /**
                                         \* Magento 2 only accept max length of store name = 32 chars
                                         \* So we have to check length of store name here to split
                                         */
                                        $val = $sales_order->$key;
                                        if ( in_array($key, array('store_name')) && strlen($val) > 32) {
                                            $val = substr($val, 0, 32);
                                        }
                                        $sales_order2->$key = $val;
                                    }
                                }

**Comment by quienti** [comment]
Not working for me, all my order are not migrated :/ And I had add this fix...

**Comment by philipvandebriel** [comment]
![schermafdruk 2015-11-27 12 23 10](https://cloud.githubusercontent.com/assets/15958461/11440311/d7fa7fb2-9501-11e5-8302-9532e4bbb829.png)

Sales orders complete now, start with "sales quote"

**Comment by philipvandebriel** [comment]
Hi,
Problem with sales quote need long time ( 430000 rows more ten 12 hours), is this normal ?
mod_fcgid: error reading data from FastCGI server
![schermafdruk 2015-11-28 08 16 21](https://cloud.githubusercontent.com/assets/15958461/11450662/8d8d3f76-95a8-11e5-81b4-bbfdc3f74d9d.png)

**Comment by quynhvv** [comment]
Hi guys,
Let's follow this: 
https://github.com/ubertheme/magento2_data_migration/releases/tag/v0.1.21
